export const COMMITS_PER_PAGE = 20;

export const COMMITS_ACTION_TYPE_KEYS = {
  COMMITS_LIST_PAGE_REQUEST: 'COMMITS_LIST_PAGE_REQUEST',
  COMMITS_LIST_PAGE_LOADING_ERROR: 'COMMITS_LIST_PAGE_LOADING_ERROR',
  COMMITS_LIST_PAGE_LOADED: 'COMMITS_LIST_PAGE_LOADED',
  COMMITS_LIST_UPDATED: 'COMMITS_LIST_UPDATED',
  SHOW_COMMIT_DETAILS: 'SHOW_COMMIT_DETAILS',
  PERFORMING_REQUEST: 'PERFORMING_REQUEST'
};

export function retrieveCommitsListPage(pageNumber)
{
  return {
    type: COMMITS_ACTION_TYPE_KEYS.COMMITS_LIST_PAGE_REQUEST,
    pageNumber,
    limit: COMMITS_PER_PAGE
  };
}