export const COMMITS_ACTION_TYPE_KEYS = {
  COMMITS_LIST_UPDATED: 'COMMITS_LIST_UPDATED',
  SHOW_COMMIT_DETAILS: 'SHOW_COMMIT_DETAILS',
  EDIT_COMMIT: 'EDIT_COMMIT',
  PERFORMING_REQUEST: 'PERFORMING_REQUEST',
  COMMIT_REMOVED: 'COMMIT_REMOVED'        // really needed?
};

// TO BE COMPLETED