export const PROGRAMMER_ACTION_TYPE = {
  ADD_ELEMENT_REQUEST: 'PROGRAMMER_ADD_ELEMENT_REQUEST',
  ADD_ELEMENT_SUCCESSFUL: 'PROGRAMMER_ADD_ELEMENT_SUCCESSFUL',
  ADD_ELEMENT_FAILED: 'PROGRAMMER_ADD_ELEMENT_FAILED',
  GET_SHORT_LIST_REQUEST: 'PROGRAMMER_GET_SHORT_LIST_REQUEST',
  GET_SHORT_LIST_SUCCESSFUL: 'PROGRAMMER_GET_SHORT_LIST_SUCCESSFUL',
  GET_SHORT_LIST_FAILED: 'PROGRAMMER_GET_SHORT_LIST_FAILED',
  RESET_UI_STATE: 'RESET_UI_STATE'
};

export function addElementAction(elementType, payload) {
  return {
    type: PROGRAMMER_ACTION_TYPE.ADD_ELEMENT_REQUEST,
    elementType,
    payload
  };
}

export function getShortListForElementAction(elementType) {
  return {
    type: PROGRAMMER_ACTION_TYPE.GET_SHORT_LIST_REQUEST,
    elementType
  };
}

export function resetUiStateAction() {
  return {
    type: PROGRAMMER_ACTION_TYPE.RESET_UI_STATE
  };
}
